#+typ_todo: BUG(b) ENH(e) DOC(d) | DONE(n) CANCELED(c@)
#+tags: maybe


* General

** BUG Inconsistent face highlighting

Some citekeys are not highlighed until the surrounding text is altered.

** ENH Citekey selection if locating fails

** ENH Function for getting all citekeys in notes

Perhaps use a cache file. This could be used in
`bog-search-citekey-on-web' and `bog-rename-staged-pdf-to-citekey'.

** DONE [#A] Add README
   CLOSED: [2014-02-03 Mon 01:53]

** DONE Describe BibTeX autokey settings for `bog-citekey-format'
   CLOSED: [2014-02-08 Sat 00:32]

** DOC Mention useful tools

- projectile: Store the notes files in git directory and use projectile
  to manage as project.
- git annex: Store and sync associated PDF files using git annex.

** DOC Installation instructions

** DONE Suggest keybindings
   CLOSED: [2014-02-08 Sat 02:37]

* Notes

** DONE [#A] Allow citekeys to be properties instead of headings
   CLOSED: [2014-02-06 Thu 00:31]

** ENH Find in-text citekeys that don't have a header

** ENH Check for duplicate citekeys headings

** ENH Refiling for just bib notes

Redefine org refile targets.

* BibTeX files

** DONE [#A] Make `bog-find-citekey-bib' compatible with a single BibTeX file
   CLOSED: [2014-02-07 Fri 01:16]

** ENH Create combined bib from a suffix glob

For documents generated from multiple files

Default could be "*.tex".

** DONE Use a stage for new BibTeX files
   CLOSED: [2014-02-15 Sat 15:06]

Avoid filtering all bib file names.

* PDF files

** ENH Better handling of multiple PDFs

If multiple PDFs for a citekey, complete read.

** DONE Map basename to full name for PDF rename
   CLOSED: [2014-02-15 Sat 15:07]

When more than one file in staged, completing read prompts with full
paths, which is inconvenient if using default completing read function.

* Testing

** ENH Ability to run tests from makefile

** CANCELED Switch from obsolete `flet' to `noflet'
   CLOSED: [2014-02-12 Wed 00:50]
   - State "CANCELED"   from "ENH"        [2014-02-12 Wed 00:50] \\
     Removed `flet`, but with set up of `bog-citekey-action', a replacement
     funciton can be passed instead of using `noflet`.
