#+typ_todo: BUG(b) ENH(e) DOC(d) | DONE(n) CANCELED(c@)
#+tags: maybe


* General

** BUG Inconsistent face highlighting

Some citekeys are not highlighed until the surrounding text is altered.

** ENH Function for getting all citekeys in notes

Perhaps use a cache file. This could be used in
`bog-search-citekey-on-web' and `bog-rename-staged-pdf-to-citekey'.

** DOC Mention useful tools

- projectile: Store the notes files in git directory and use projectile
  to manage as project.
- git annex: Store and sync associated PDF files using git annex.

** DOC Installation instructions

* Notes

** ENH Find in-text citekeys that don't have a header

** ENH Check for duplicate citekeys headings

** ENH Make bog-goto functions work when citekey is property

Currently, `bog-goto-citekey-heading-in-buffer' and
`bog-goto-citekey-heading-in-notes' only work if the citekey is stored
as a heading, not a property.

* BibTeX files

** ENH Create combined bib from a suffix glob

For documents generated from multiple files

Default could be "*.tex".

* PDF files

** ENH Use `org-file-apps' instead of `bog-pdf-opener'

* Testing

** ENH Ability to run tests from makefile

** ENH Put some of the common setup in macros

I'm thinking mainly of temporary Org buffers.

* Release archive                                                   :ARCHIVE:

** v0.6.0
*** CANCELED Switch from obsolete `flet' to `noflet'
    CLOSED: [2014-02-12 Wed 00:50]
    - State "CANCELED"   from "ENH"        [2014-02-12 Wed 00:50] \\
      Removed `flet`, but with set up of `bog-citekey-action', a replacement
      funciton can be passed instead of using `noflet`.

*** DONE Map basename to full name for PDF rename
   CLOSED: [2014-02-15 Sat 15:07]

When more than one file in staged, completing read prompts with full
paths, which is inconvenient if using default completing read function.

*** DONE Better handling of multiple PDFs
   CLOSED: [2014-03-04 Tue 00:49]

If multiple PDFs for a citekey, complete read.

*** DONE Use a stage for new BibTeX files
   CLOSED: [2014-02-15 Sat 15:06]

Avoid filtering all bib file names.

*** DONE [#A] Make `bog-find-citekey-bib' compatible with a single BibTeX file
    CLOSED: [2014-02-07 Fri 01:16]

*** DONE Refiling for just bib notes
   CLOSED: [2014-02-16 Sun 00:40]

Redefine org refile targets.

*** DONE [#A] Allow citekeys to be properties instead of headings
    CLOSED: [2014-02-06 Thu 00:31]

*** DONE Suggest keybindings
    CLOSED: [2014-02-08 Sat 02:37]

*** DONE Describe BibTeX autokey settings for `bog-citekey-format'
    CLOSED: [2014-02-08 Sat 00:32]

*** CANCELED Citekey selection if locating fails
    CLOSED: [2014-03-16 Sun 17:59]
    - State "CANCELED"   from "ENH"        [2014-03-16 Sun 17:59] \\
      For now, I will stick to issuing an error message if no citekey is
      found, and only prompting if a prefix argument is given.

*** DONE [#A] Add README
    CLOSED: [2014-02-03 Mon 01:53]
